#!/bin/bash
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <file>"
  exit 1
fi
file="$1"
if [ ! -f "$file" ]; then
  echo "Error: File '$file' not found."
  exit 1
fi
check_alert() {
  url="$1"
  endpoint="$2"
  source_code=$(curl -s "$url")
  if [[ $source_code =~ "alert(1)" ]]; then
    echo "Vulnerable endpoint found: $endpoint in URL: $url"
  fi
}
while IFS= read -r line; do
endpoint=$(basename "$line")
  check_alert "$line" "$endpoint"
done < "$file"
